//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTChess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LTChess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: 1/35 (rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1)
        ///a2a3: 8457
        ///b2b3: 9345
        ///c2c3: 9272
        ///d2d3: 11959
        ///e2e3: 13134
        ///f2f3: 8457
        ///g2g3: 9345
        ///h2h3: 8457
        ///a2a4: 9329
        ///b2b4: 9332
        ///c2c4: 9744
        ///d2d4: 12435
        ///e2e4: 13160
        ///f2f4: 8929
        ///g2g4: 9328
        ///h2h4: 9329
        ///b1a3: 8885
        ///b1c3: 9755
        ///g1f3: 9748
        ///g1h3: 8881
        ///
        ///Nodes searched: 197281
        ///
        ///
        ///Position: 2/35 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)
        ///a2a3: 94405
        ///b2b3: 81066
        ///g2g3: 77468
        ///d5d6: 79551
        ///a2a4: 90978
        ///g2g4: 7567 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sf14bench_perft4 {
            get {
                return ResourceManager.GetString("sf14bench_perft4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: 1/47 (rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1)
        ///a2a3: 181046
        ///b2b3: 215255
        ///c2c3: 222861
        ///d2d3: 328511
        ///e2e3: 402988
        ///f2f3: 178889
        ///g2g3: 217210
        ///h2h3: 181044
        ///a2a4: 217832
        ///b2b4: 216145
        ///c2c4: 240082
        ///d2d4: 361790
        ///e2e4: 405385
        ///f2f4: 198473
        ///g2g4: 214048
        ///h2h4: 218829
        ///b1a3: 198572
        ///b1c3: 234656
        ///g1f3: 233491
        ///g1h3: 198502
        ///
        ///Nodes searched: 4865609
        ///
        ///
        ///Position: 2/47 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)
        ///a2a3: 4627439
        ///b2b3: 3768824
        ///g2g3: 34 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sf14bench_perft5 {
            get {
                return ResourceManager.GetString("sf14bench_perft5", resourceCulture);
            }
        }
    }
}
