//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureWeight:[3,0,-8,7,4,-1,-9,-3,-8,-8,2,-7,-8,-7,4,2,8,9,7,-4,-3,-4,-5,-3,-8,5,8,0,-4,1,2,0,-2,-3,6,-3,-6,6,3,5,-5,7,-3,-1,-8,2,-8,-7,3,-4,3,8,-1,-2,8,-8,-8,-8,4,8,-1,-8,2,-2,-7,9,-3,3,-1,-4,-8,-6,4,2,5,-3,1,-7,2,2,0,-4,-1,7,-8,-3,-6,-8,-9,5,4,-1,1,3,-6,2,-2,1,3,-7,-4,-5,2,1,-6,-3,4,-3,-8,3,1,-9,-7,-7,4,-5,2,0,7,0,-4,0,2,5,8,7,8,-6,2,0,7,0,6,-2,7,-6,-3,-9,-4,-4,-2,0,2,9,0,0,-9,4,-8,-6,-1,5,8,4,0,3,8,-6,0,3,2,-7,0,4,-1,3,1,-8,-3,7,-9,-3,-1,-6,3,-4,5,-2,3,-8,-9,-8,2,-8,-7,-1,-6,-5,3,-7,0,-2,-5,0,-5,-1,2,4, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
    }
}
